// Generated by CoffeeScript 1.10.0
(function() {
  window.Animal = (function() {
    function Animal() {}

    Animal.behaviors = function() {
      switch (this.type) {
        case "cat":
          return ["meow", null];
        case "dog":
          return ["bark", "wag"];
        case "rabbit":
          return [null, "hop hop"];
        case "horse":
        case "donkey":
          return ["neigh", null];
        default:
          return [null, null];
      }
    };

    Animal.fromHash = function(data) {
      var animal, key, val;
      animal = new this;
      for (key in data) {
        val = data[key];
        animal[key] = val;
      }
      return animal;
    };

    Animal.loadSeedData = function() {
      var animal, animalData, i, len, results;
      animalData = [
        {
          name: "Keylsey",
          type: "dog",
          age: 2,
          bread: "Labrador",
          description: "A sweet and loyal dog."
        }
      ];
      results = [];
      for (i = 0, len = animalData.length; i < len; i++) {
        animal = animalData[i];
        results.push(this.fromHash(animal));
      }
      return results;
    };

    return Animal;

  })();

}).call(this);
