// Generated by CoffeeScript 1.10.0
(function() {
  var Airplane;

  Airplane = (function() {
    function Airplane() {}

    Airplane.prototype.takeoff = function() {
      return console.log("Vrrrroooom!");
    };

    return Airplane;

  })();

}).call(this);
