// Generated by CoffeeScript 1.10.0
(function() {
  var Automobile, Hatchback, PoliceCar, Truck, myCar,
    extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    hasProp = {}.hasOwnProperty;

  Automobile = (function() {
    function Automobile() {}

    Automobile.prototype.honk = function() {
      return console.log("Beep!");
    };

    return Automobile;

  })();

  Hatchback = (function(superClass) {
    extend(Hatchback, superClass);

    function Hatchback() {
      return Hatchback.__super__.constructor.apply(this, arguments);
    }

    Hatchback.prototype.carAlarm = function() {
      this.honk();
      this.honk();
      return this.honk();
    };

    return Hatchback;

  })(Automobile);

  myCar = new Hatchback();

  myCar.honk();

  myCar.carAlarm();

  Truck = (function(superClass) {
    var trunk;

    extend(Truck, superClass);

    function Truck() {
      return Truck.__super__.constructor.apply(this, arguments);
    }

    Truck.prototype.honk = function() {
      return console.log("BRAAAAAP");
    };

    Truck.prototype.radio = function(volume) {
      return Truck.__super__.radio.call(this, volume + 2);
    };

    trunk = new Trunk;

    trunk.radio(9);

    return Truck;

  })(Automobile);

  PoliceCar = (function(superClass) {
    extend(PoliceCar, superClass);

    function PoliceCar() {
      return PoliceCar.__super__.constructor.apply(this, arguments);
    }

    PoliceCar.prototype.honk = function() {
      PoliceCar.__super__.honk.apply(this, arguments);
      return console.log("Wee-oo wee-oo wee-oo");
    };

    return PoliceCar;

  })(Automobile);

}).call(this);
