// Generated by CoffeeScript 1.10.0
(function() {
  var evenNubmers, i, len, n, word, words;

  words = ["dogma", "catastrophe", "doggerel", "hangdog"];

  for (i = 0, len = words.length; i < len; i++) {
    word = words[i];
    if (word.indexOf("dog") !== -1) {
      console.log(word);
    }
  }

  evenNubmers = (function() {
    var j, results;
    results = [];
    for (n = j = 1; j <= 100; n = ++j) {
      if (n % 2 === 0) {
        results.push(n + "is even");
      }
    }
    return results;
  })();

}).call(this);
