// Generated by CoffeeScript 1.10.0
(function() {
  var animal, animals, animals2, bigNumbers, end, i, j, k, language, len, len1, mute, playingMusic, power, results, start;

  power = true;

  mute = false;

  if (power === true) {
    if (mute === false) {
      playingMusic = true;
    }
  } else {
    playingMusic = false;
  }

  language = ["english", "spanish", "french"];

  console.log(language[1]);

  start = 0;

  end = 2000;

  bigNumbers = (function() {
    results = [];
    for (var i = start; start <= end ? i <= end : i >= end; start <= end ? i++ : i--){ results.push(i); }
    return results;
  }).apply(this);

  console.log("========================================>");

  animals = ["dog", "cat", "bird"];

  for (j = 0, len = animals.length; j < len; j++) {
    animal = animals[j];
    console.log(animal);
  }

  animals2 = ["dog", "cat", "bird"];

  for (k = 0, len1 = animals2.length; k < len1; k++) {
    animal = animals2[k];
    console.log(animal);
  }

}).call(this);
