// Generated by CoffeeScript 1.10.0
(function() {
  var animalBehaviors, chosenPetName, fullListIndex, i, j, len, nameElement, pet, ref, ref1, shop;

  shop = {
    owner: new Person("Jess"),
    animals: Animal.loadSeedData()
  };

  nameElement = document.getElementById("owner_name");

  nameElement.innerHTML = shop.owner.possessiveName();

  document.title = (shop.owner.possessiveName()) + " Pet shop";

  ref = shop.animals;
  for (i = j = 0, len = ref.length; j < len; i = ++j) {
    pet = ref[i];
    if (pet.name === chosenPetName) {
      ref1 = [pet, i], chosenPetName = ref1[0], fullListIndex = ref1[1];
    }
  }

  animalBehaviors = function(animal) {
    switch (animal.type) {
      case "cat":
        return ["meow", null];
      case "dog":
        return ["bark", "wag"];
      case "rabbit":
        return [null, "hop hop"];
      case "horse":
      case "donkey":
        return ["neigh", null];
      default:
        return [null, null];
    }
  };

}).call(this);
