// Generated by CoffeeScript 1.10.0
(function() {
  var Bicycle, myBike;

  Bicycle = (function() {
    function Bicycle(color1, size, frameType, tireWidth, handlebarType) {
      this.color = color1;
      this.size = size;
      this.frameType = frameType;
      this.tireWidth = tireWidth;
      this.handlebarType = handlebarType;
    }

    Bicycle.frameSizeByHeight = function(riderHeight) {
      return Math.floor(riderHeight * 0.82);
    };

    Bicycle.buildPackageDeal = function(color, type, riderHeight) {
      var args, basics, details;
      basics = [color, this.frameSizeByHeight(riderHeight)];
      details = (function() {
        switch (type) {
          case "road":
            return ["road", "23c", "drop bars"];
          case "commuter":
            return ["road", "30c", "flat bars"];
          case "mountain":
            return ["mountain", "2in", "flat bars"];
        }
      })();
      args = basics.concat(details);
      return (function(func, args, ctor) {
        ctor.prototype = func.prototype;
        var child = new ctor, result = func.apply(child, args);
        return Object(result) === result ? result : child;
      })(Bicycle, args, function(){});
    };

    return Bicycle;

  })();

  myBike = Bicycle.buildPackageDeal("black", "commuter", 66);

}).call(this);
